version: "2.1"
networks:
    php-net:
      driver: bridge
services:
  cnps:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: CNPS
    networks:
      - php-net
    volumes:
      - ./var/www:/var/www
      - ./php/php.ini:/etc/php.ini
      - ./php/php.d/10-opcache.ini:/etc/php.d/10-opcache.ini
      - ./php/php-fpm.conf:/etc/php-fpm.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
    ports:
      - "80:80"
      - 8080-8180:8080-8180
      - "443:443"
      - "3002:3002"
    restart: always
  mysql:
    image: mysql:5.7
    container_name: Mysql
    networks:
      - php-net
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: A123456
        TZ: Asia/Shanghai
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/data/backup
      - ./mysql/log:/var/log
    ports:
      - "3306:3306"
    restart: always
    privileged: true
  redmine:
    build:
      context: ./
      dockerfile: DockerRedminefile
    container_name: redmine
    ports:
      - 3000:3000
    networks:
      - php-net
    volumes:
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - ./redmine/data:/usr/src/redmine/files
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    environment:
      - REDMINE_DB_MYSQL=192.168.3.99
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=root
      - REDMINE_DB_PASSWORD=A123456
      - REDMINE_PLUGINS_MIGRATE=true
    restart: always
  # gitlab:
  #   image: gitlab/gitlab-ce:12.3.5-ce.0
  #   restart: always
  #   container_name: gitlab
  #   environment:
  #     TZ: Asia/Shanghai
  #   networks:
  #     - php-net
  #   ports:
  #     - "9980:80"
  #     - "9922:22"
  #   networks:
  #     - php-net
  #   volumes:
  #     - ./gitlab/etc:/etc/gitlab
  #     - ./gitlab/log:/var/log/gitlab
  #     - ./gitlab/opt:/var/opt/gitlab
  #   privileged: true
  # svn:
  #   image: elleflorio/svn-server:latest
  #   restart: always
  #   container_name: svn
  #   environment:
  #     TZ: Asia/Shanghai
  #   networks:
  #     - php-net
  #   ports:
  #     - "9090:80"
  #     - "3690:3690"
  #   networks:
  #     - php-net
  #   volumes:
  #     - ./svn:/home/svn
  #   privileged: true